server:
  port: 9090
spring:
  application:
    name: product-service-apollo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      zone: jieyang
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    availability-zones:
      guangdong: jieyang,shantou
    region: guangdong
    service-url:
      jieyang: http://localhost:8080/eureka/,http://localhost:8081/eureka/
      shantou: http://localhost:8082/eureka/

apollo:
  bootstrap: #开启apollo
    enabled: true
  meta: http://localhost:8080 #开启apollo服务端的时候默认会启动自己的eureka，这个就是eureka地址
app:
  id: product-service #指定apollo配置中心中的appid

apolloInfo: 123456


